### ISSUE TITLE
python auth.py 执行错误 ，为什么阿。pythonpath 环境变量已经设置

### ISSUE THREAD

**Issue by feifly329** [MyDuerOS/DuerOS-Python-Client#1]
Traceback (most recent call last):
  File "dueros/auth.py", line 11, in <module>
    import dueros.config
ImportError: No module named config

**Comment by feiyx** [comment]
是的，同遇到问题。

**Comment by CaiquanLiu** [comment]
# export PYTHONPATH=xxx/MyAssistant:$PYTHONPATH
使用绝对路径
